# Import

In [ ]:
import pandas as pd

# Loading the DataFrame

/var/folders/7q/2wc5cs997tqgvx852w8yrf1r0000gn/T/ipykernel_68070/1396930603.py:7: DtypeWarning:

Columns (3,12) have mixed types. Specify dtype option on import or set low_memory=False.

# Data Exploration

In [9]:
df1.head()

,club_name,player_name,age,position,club_involved_name,fee,transfer_movement,transfer_period,fee_cleaned,league_name,year,season,country
0,Middlesbrough FC,Tommy Wright,26.0,Left Winger,Leicester,€910Th.,in,Summer,0.91,Premier League,1992,1992/1993,England
1,Middlesbrough FC,Jonathan Gittens,28.0,defence,Southampton,€250Th.,in,Summer,0.25,Premier League,1992,1992/1993,England
2,Middlesbrough FC,Chris Morris,28.0,Right-Back,Celtic,?,in,Summer,NaN,Premier League,1992,1992/1993,England
3,Middlesbrough FC,Ben Roberts,17.0,Goalkeeper,Boro U18,-,in,Summer,NaN,Premier League,1992,1992/1993,England
4,Middlesbrough FC,Andy Todd,17.0,Centre-Back,Boro U18,-,in,Summer,NaN,Premier League,1992,1992/1993,England

In [19]:
df1.shape

(23675, 13)

In [12]:
df1["year"].min(), df1["year"].max()

(1992, 2022)

In [13]:
df1["season"].min(), df1["season"].max()

('1992/1993', '2022/2023')

- This dataset has only data upto 2023, scope is upto season 23-24.

In [23]:
df1["league_name"].value_counts()

league_name
Premier League    23675
Name: count, dtype: int64

- No second division teams included

## La Liga - Spanish League

In [15]:
df2.head()

,club_name,player_name,age,position,club_involved_name,fee,transfer_movement,transfer_period,fee_cleaned,league_name,year,season,country
0,Real Sociedad,Alberto López,23.0,Goalkeeper,Real Sociedad B,-,in,Summer,NaN,Primera Division,1992,1992/1993,Spain
1,Real Sociedad,Iñigo Idiakez,18.0,Attacking Midfield,R. Sociedad U19,-,in,Summer,NaN,Primera Division,1992,1992/1993,Spain
2,Real Sociedad,José González,27.0,Goalkeeper,Valencia,?,out,Summer,NaN,Primera Division,1992,1992/1993,Spain
3,Cádiz CF,Igor Stimac,24.0,Centre-Back,Hajduk Split,?,in,Summer,NaN,Primera Division,1992,1992/1993,Spain
4,Cádiz CF,Quino,21.0,attack,CD Málaga,?,in,Summer,NaN,Primera Division,1992,1992/1993,Spain

In [16]:
df2["year"].min(), df2["year"].max()

(1992, 2022)

In [17]:
df2["season"].min(), df2["season"].max()

('1992/1993', '2022/2023')

In [24]:
df2["league_name"].value_counts()

league_name
Primera Division    17380
Name: count, dtype: int64

## Bundesliga - German League

In [20]:
df3.head()

,club_name,player_name,age,position,club_involved_name,fee,transfer_movement,transfer_period,fee_cleaned,league_name,year,season,country
0,1.FC Saarbrücken,Thomas Stratos,25.0,Defensive Midfield,Hamburger SV,€150Th.,in,Summer,0.15,1 Bundesliga,1992,1992/1993,Germany
1,1.FC Saarbrücken,Matthias Lust,22.0,Left Midfield,Waldh. Mannheim,free transfer,in,Summer,0.00,1 Bundesliga,1992,1992/1993,Germany
2,1.FC Saarbrücken,Henning Bürger,22.0,Left Midfield,FC Schalke 04,free transfer,in,Summer,0.00,1 Bundesliga,1992,1992/1993,Germany
3,1.FC Saarbrücken,Michael Hennig,20.0,midfield,FC Berlin,free transfer,in,Summer,0.00,1 Bundesliga,1992,1992/1993,Germany
4,1.FC Saarbrücken,Malik Badji,24.0,defence,CS Sedan,?,in,Summer,NaN,1 Bundesliga,1992,1992/1993,Germany

In [21]:
df3["year"].min(), df3["year"].max()

(1992, 2022)

In [22]:
df3["season"].min(), df3["season"].max()

('1992/1993', '2022/2023')

In [25]:
df3["league_name"].value_counts()

league_name
1 Bundesliga    14158
Name: count, dtype: int64

## Ligue 1 - French League

In [26]:
df4.head()

,club_name,player_name,age,position,club_involved_name,fee,transfer_movement,transfer_period,fee_cleaned,league_name,year,season,country
0,AC Le Havre,Didier Angibeaud,17.0,Centre-Forward,Unknown,?,in,Summer,NaN,Ligue 1,1992,1992/1993,France
1,AC Le Havre,Jean-Roch Testa,27.0,attack,FC Gueugnon,?,in,Summer,NaN,Ligue 1,1992,1992/1993,France
2,AC Le Havre,Gia Guruli,28.0,Centre-Forward,GKS Katowice,?,in,Summer,NaN,Ligue 1,1992,1992/1993,France
3,AC Le Havre,Michel Rio,29.0,Attacking Midfield,SM Caen,?,in,Summer,NaN,Ligue 1,1992,1992/1993,France
4,AC Le Havre,Christophe Revault,20.0,Goalkeeper,Le Havre B,-,in,Summer,NaN,Ligue 1,1992,1992/1993,France

In [27]:
df4["year"].min(), df4["year"].max()

(1992, 2022)

In [28]:
df4["season"].min(), df4["season"].max()

('1992/1993', '2022/2023')

In [29]:
df4["league_name"].value_counts()

league_name
Ligue 1    17580
Name: count, dtype: int64

## Serie A - Italian League

In [30]:
df5.head()

,club_name,player_name,age,position,club_involved_name,fee,transfer_movement,transfer_period,fee_cleaned,league_name,year,season,country
0,AC Fiorentina,Brian Laudrup,23.0,Right Winger,Bayern Munich,€5.00m,in,Summer,5.00,Serie A,1992,1992/1993,Italy
1,AC Fiorentina,Stefan Effenberg,23.0,Central Midfield,Bayern Munich,€3.75m,in,Summer,3.75,Serie A,1992,1992/1993,Italy
2,AC Fiorentina,Daniele Carnasciali,25.0,Right-Back,Brescia,?,in,Summer,NaN,Serie A,1992,1992/1993,Italy
3,AC Fiorentina,Diego Latorre,22.0,Second Striker,Boca Juniors,?,in,Summer,NaN,Serie A,1992,1992/1993,Italy
4,AC Fiorentina,Andrea Vascotto,20.0,midfield,Barletta CS,?,in,Summer,NaN,Serie A,1992,1992/1993,Italy

In [31]:
df5["year"].min(), df5["year"].max()

(1992, 2022)

In [32]:
df5["season"].min(), df5["season"].max()

('1992/1993', '2022/2023')

In [33]:
df5["league_name"].value_counts()

league_name
Serie A    28433
Name: count, dtype: int64

# Team Performance Dataset

In [35]:
df_perf.shape

(113514, 25)

In [36]:
df_perf.head()

,Season,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,22-23,Premier League,05/08/2022,20:00,Crystal Palace,Arsenal,0.0,2.0,A,0.0,...,2.0,2.0,16.0,11.0,3.0,5.0,1.0,2.0,0.0,0.0
1,22-23,Premier League,06/08/2022,12:30,Fulham,Liverpool,2.0,2.0,D,1.0,...,3.0,4.0,7.0,9.0,4.0,4.0,2.0,0.0,0.0,0.0
2,22-23,Premier League,06/08/2022,15:00,Bournemouth,Aston Villa,2.0,0.0,H,1.0,...,3.0,2.0,18.0,16.0,5.0,5.0,3.0,3.0,0.0,0.0
3,22-23,Premier League,06/08/2022,15:00,Leeds,Wolves,2.0,1.0,H,1.0,...,4.0,6.0,13.0,9.0,6.0,4.0,2.0,0.0,0.0,0.0
4,22-23,Premier League,06/08/2022,15:00,Newcastle,Nott'm Forest,2.0,0.0,H,0.0,...,10.0,0.0,9.0,14.0,11.0,1.0,0.0,3.0,0.0,0.0

In [37]:
df_perf.tail()

,Season,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
113509,93-94,LaLiga,15/05/94,NaN,Osasuna,Sp Gijon,3.0,0.0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113510,93-94,LaLiga,15/05/94,NaN,Oviedo,Logrones,1.0,2.0,A,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113511,93-94,LaLiga,15/05/94,NaN,Santander,Lerida,2.0,1.0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113512,93-94,LaLiga,15/05/94,NaN,Valladolid,Celta,0.0,0.0,D,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113513,93-94,LaLiga,15/05/94,NaN,Zaragoza,Real Madrid,4.0,1.0,H,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- Time period needs to be filtered
- Too many columns, only those relevant need to be filtered

In [40]:
df_perf["Div"].value_counts()

Div
EFL Championship    16560
LaLiga 2            12392
Premier League      11564
LaLiga              11564
Serie B             11162
Ligue 1             10929
Serie A             10586
Ligue 2             10323
Bundesliga 2         9254
Bundesliga           9180
Name: count, dtype: int64

- Second division teams to be removed

# Transfer and Performance Dataset

In [43]:
df_clubs.columns

Index(['club_id', 'club_code', 'name', 'domestic_competition_id',
       'total_market_value', 'squad_size', 'average_age', 'foreigners_number',
       'foreigners_percentage', 'national_team_players', 'stadium_name',
       'stadium_seats', 'net_transfer_record', 'coach_name', 'last_season',
       'filename', 'url'],
      dtype='object')

In [44]:
df_comps.columns

Index(['competition_id', 'competition_code', 'name', 'sub_type', 'type',
       'country_id', 'country_name', 'domestic_league_code', 'confederation',
       'url', 'is_major_national_league'],
      dtype='object')

In [46]:
df_games.columns

Index(['game_id', 'competition_id', 'season', 'round', 'date', 'home_club_id',
       'away_club_id', 'home_club_goals', 'away_club_goals',
       'home_club_position', 'away_club_position', 'home_club_manager_name',
       'away_club_manager_name', 'stadium', 'attendance', 'referee', 'url',
       'home_club_formation', 'away_club_formation', 'home_club_name',
       'away_club_name', 'aggregate', 'competition_type'],
      dtype='object')

In [47]:
df_transfers.columns

Index(['player_id', 'transfer_date', 'transfer_season', 'from_club_id',
       'to_club_id', 'from_club_name', 'to_club_name', 'transfer_fee',
       'market_value_in_eur', 'player_name'],
      dtype='object')

In [48]:
df_comps["name"].unique()

array(['jupiler-pro-league', 'belgian-supercup', 'copa-del-rey',
       'efl-cup', 'italy-cup', 'uefa-champions-league',
       'uefa-champions-league-qualifikation', 'dfb-pokal', 'dfl-supercup',
       'superligaen', 'sydbank-pokalen',
       'uefa-europa-conference-league-qualifikation', 'europa-league',
       'europa-league-qualifikation', 'laliga', 'fa-cup', 'ligue-1',
       'trophee-des-champions', 'premier-league', 'community-shield',
       'super-league-1', 'kypello-elladas', 'serie-a', 'fifa-klub-wm',
       'bundesliga', 'eredivisie', 'toto-knvb-beker',
       'johan-cruijff-schaal', 'liga-portugal-bwin', 'allianz-cup',
       'supertaca-candido-de-oliveira', 'premier-liga', 'russian-cup',
       'russian-super-cup', 'scottish-premiership', 'supercoppa-italiana',
       'sfa-cup', 'supercopa', 'super-lig', 'uefa-conference-league',
       'ukrainian-cup', 'ukrainian-super-cup', 'uefa-super-cup'],
      dtype=object)

In [49]:
df_comps[["competition_id", "competition_code", "name"]].head(20)

,competition_id,competition_code,name
0,BE1,jupiler-pro-league,jupiler-pro-league
1,BESC,belgian-supercup,belgian-supercup
2,CDR,copa-del-rey,copa-del-rey
3,CGB,efl-cup,efl-cup
4,CIT,italy-cup,italy-cup
5,CL,uefa-champions-league,uefa-champions-league
6,CLQ,uefa-champions-league-qualifikation,uefa-champions-league-qualifikation
7,DFB,dfb-pokal,dfb-pokal
8,DFL,dfl-supercup,dfl-supercup
9,DK1,superligaen,superligaen
10,DKP,sydbank-pokalen,sydbank-pokalen
11,ECLQ,uefa-europa-conference-league-qualifikation,uefa-europa-conference-league-qualifikation
12,EL,europa-league,europa-league
13,ELQ,europa-league-qualifikation,europa-league-qualifikation
14,ES1,laliga,laliga
15,FAC,fa-cup,fa-cup
16,FR1,ligue-1,ligue-1
17,FRCH,trophee-des-champions,trophee-des-champions
18,GB1,premier-league,premier-league
19,GBCS,community-shield,community-shield